/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Payment {
  bill_id: number;
  created_on: number;
  creator: string;
  id: Generated<number | null>;
  share_code: string;
}

export interface PaymentLineItem {
  amount: number;
  id: Generated<number | null>;
  line_item_id: number;
  payment_id: number;
}

export interface ScannedBill {
  created_on: number;
  currency: string | null;
  date: string | null;
  file_name: string;
  id: Generated<number | null>;
  name: string | null;
  share_code: string;
}

export interface ScannedBillLineItem {
  amount: number;
  bill_id: number;
  description: string;
  id: Generated<number | null>;
  total_price: number;
}

export interface SubmittedBill {
  created_on: number;
  currency: string;
  date: string;
  file_name: string;
  id: Generated<number | null>;
  name: string;
  number_of_payments: Generated<number>;
  payment_method: string;
  service_fee: number | null;
  share_code: string;
}

export interface SubmittedBillLineItem {
  amount: number;
  bill_id: number;
  description: string;
  id: Generated<number | null>;
  unit_price: number;
}

export interface DB {
  payment: Payment;
  payment_line_item: PaymentLineItem;
  scanned_bill: ScannedBill;
  scanned_bill_line_item: ScannedBillLineItem;
  submitted_bill: SubmittedBill;
  submitted_bill_line_item: SubmittedBillLineItem;
}
