name: billy-split

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Build container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker build --platform=linux/arm64 --tag $REGISTRY_URL/billy-split:$REGISTRY_IMAGE_TAG --tag $REGISTRY_URL/billy-split:latest .
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_IMAGE_TAG: ${{ github.sha }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE_NAME: ${{ github.sha }}

      - name: Deploy container to server
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          eval "$(ssh-agent -s)"
          echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "$DEPLOY_SSH_KEYSCAN" > ~/.ssh/known_hosts

          # Push container to registry
          echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL --username $REGISTRY_USERNAME --password-stdin
          docker push $REGISTRY_URL/billy-split --all-tags
          docker logout

          # Redeploy stack on server
          scp -i ~/.ssh/deploy_key -P "$DEPLOY_SSH_SERVER_PORT" "docker-compose.prod.yml" "$DEPLOY_SSH_USERNAME@$DEPLOY_SSH_SERVER":~/billy-split/docker-compose.yml
          ssh -i ~/.ssh/deploy_key -p "$DEPLOY_SSH_SERVER_PORT" -l "$DEPLOY_SSH_USERNAME" "$DEPLOY_SSH_SERVER" "cd billy-split; docker compose pull && docker compose up -d"
        env:
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_SSH_KEYSCAN: ${{ secrets.DEPLOY_SSH_KEYSCAN }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_IMAGE_TAG: ${{ github.sha }}
          DEPLOY_SSH_SERVER: ${{ secrets.DEPLOY_SSH_SERVER }}
          DEPLOY_SSH_SERVER_PORT: ${{ secrets.DEPLOY_SSH_SERVER_PORT }}
          DEPLOY_SSH_USERNAME: ${{ secrets.DEPLOY_SSH_USERNAME }}
